export type Company = {
    id: string;
    companyKey: string;
    displayName: string;
    legalName?: string | null;
    tagline?: string | null;
    timezone?: string | null;
    supportEmail?: string | null;
    supportPhone?: string | null;
    supportHours?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    addressCity?: string | null;
    addressState?: string | null;
    addressPostalCode?: string | null;
    addressCountry?: string | null;
    webBaseUrl?: string | null;
    apiBaseUrl?: string | null;
    helpCenterUrl?: string | null;
    privacyPolicyUrl?: string | null;
    termsUrl?: string | null;
    unsubscribeUrl?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    x?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    whatsapp?: string | null;
    telegram?: string | null;
    copyrightText?: string | null;
    disclaimerShort?: string | null;
    disclaimerLong?: string | null;
    logoIconUrl?: string | null;
    logoFullUrl?: string | null;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string;
};

export type UpdateCompanyDto = Partial<Omit<Company, "id" | "createdAt" | "updatedAt">>;