/**
 * Constants used by the one-click calendar setup endpoints.
 * Change values here — do not duplicate them across service/controller layers.
 */
export const CALENDAR_SETUP_DEFAULTS = {
  /** Default name for the automatically created payment calendar. */
  PAYMENT_CALENDAR_NAME:        'Shift Payments',
  PAYMENT_CALENDAR_DESCRIPTION: 'Expected invoice payment dates generated by Business App.',

  /** Key of the verified Australian national public holiday catalogue entry. */
  AU_HOLIDAY_CATALOGUE_KEY: 'au_national_public_holidays',

  /** User-facing message when the calendar provider does not support URL subscription. */
  AU_HOLIDAY_UNAVAILABLE_MESSAGE:
    'Automatic holiday subscription is not supported by this calendar provider.',
} as const;
