"""initial_data_warehouse_schema

Revision ID: 32d1d2706e72
Revises: 
Create Date: 2026-07-06 17:58:20.040678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32d1d2706e72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_business',
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('company_key', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_platform', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('business_id'),
    sa.UniqueConstraint('company_key')
    )
    op.create_table('dim_time',
    sa.Column('date_key', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_quarter', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=20), nullable=True),
    sa.Column('week_of_year', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('is_au_public_holiday', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('date_key')
    )
    op.create_table('dim_customer',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=False),
    sa.Column('abn', sa.String(length=11), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['dim_business.business_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_dim_customer_business_id'), 'dim_customer', ['business_id'], unique=False)
    op.create_table('dim_user',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=201), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['dim_business.business_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('fact_customer_activity',
    sa.Column('fact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('activity_date_key', sa.Date(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['activity_date_key'], ['dim_time.date_key'], ),
    sa.ForeignKeyConstraint(['business_id'], ['dim_business.business_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_fact_customer_activity_business_id'), 'fact_customer_activity', ['business_id'], unique=False)
    op.create_table('fact_invoice',
    sa.Column('fact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('issue_date_key', sa.Date(), nullable=True),
    sa.Column('due_date_key', sa.Date(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('is_voided', sa.Boolean(), nullable=True),
    sa.Column('work_event_count', sa.Integer(), nullable=True),
    sa.Column('days_to_due', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['dim_business.business_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['due_date_key'], ['dim_time.date_key'], ),
    sa.ForeignKeyConstraint(['issue_date_key'], ['dim_time.date_key'], ),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_fact_invoice_business_id'), 'fact_invoice', ['business_id'], unique=False)
    op.create_table('fact_payment',
    sa.Column('fact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('payment_date_key', sa.Date(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('is_reversed', sa.Boolean(), nullable=True),
    sa.Column('days_to_payment', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['dim_business.business_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['payment_date_key'], ['dim_time.date_key'], ),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_fact_payment_business_id'), 'fact_payment', ['business_id'], unique=False)
    op.create_table('fact_work_event',
    sa.Column('fact_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('business_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('work_date_key', sa.Date(), nullable=True),
    sa.Column('work_event_id', sa.UUID(), nullable=False),
    sa.Column('contract_id', sa.UUID(), nullable=True),
    sa.Column('duration_minutes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('calculated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rate_type', sa.String(length=30), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=True),
    sa.Column('is_voided', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['dim_business.business_id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_id'], ),
    sa.ForeignKeyConstraint(['work_date_key'], ['dim_time.date_key'], ),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_fact_work_event_business_id'), 'fact_work_event', ['business_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_work_event_business_id'), table_name='fact_work_event')
    op.drop_table('fact_work_event')
    op.drop_index(op.f('ix_fact_payment_business_id'), table_name='fact_payment')
    op.drop_table('fact_payment')
    op.drop_index(op.f('ix_fact_invoice_business_id'), table_name='fact_invoice')
    op.drop_table('fact_invoice')
    op.drop_index(op.f('ix_fact_customer_activity_business_id'), table_name='fact_customer_activity')
    op.drop_table('fact_customer_activity')
    op.drop_table('dim_user')
    op.drop_index(op.f('ix_dim_customer_business_id'), table_name='dim_customer')
    op.drop_table('dim_customer')
    op.drop_table('dim_time')
    op.drop_table('dim_business')
    # ### end Alembic commands ###
