"""Semantic measure definitions for the Contracts (FactContract) domain.

All measures are computed over fact_contract rows scoped by business_id.
When business_id is omitted (Platform Admin), they aggregate across all tenants.
"""

CONTRACT_MEASURES: dict = {
    # ── Totals ────────────────────────────────────────────────────────────────
    "contract_count": {
        "type": "count",
        "description": "Total number of contracts",
        "column": "id",
        "filter": None,
        "aggregations": ["count"],
        "format": "integer",
        "null_handling": "count treats null id as 0; will not occur (PK)",
    },
    "active_contract_count": {
        "type": "count",
        "description": "Contracts with status = active",
        "column": "id",
        "filter": {"status": "active"},
        "aggregations": ["count"],
        "format": "integer",
    },
    "inactive_contract_count": {
        "type": "count",
        "description": "Contracts with status = inactive",
        "column": "id",
        "filter": {"status": "inactive"},
        "aggregations": ["count"],
        "format": "integer",
    },
    "finished_contract_count": {
        "type": "count",
        "description": "Contracts with status = finished",
        "column": "id",
        "filter": {"status": "finished"},
        "aggregations": ["count"],
        "format": "integer",
    },
    "cancelled_contract_count": {
        "type": "count",
        "description": "Contracts with status = cancelled",
        "column": "id",
        "filter": {"status": "cancelled"},
        "aggregations": ["count"],
        "format": "integer",
    },
    # ── Duration pattern ──────────────────────────────────────────────────────
    "open_ended_contract_count": {
        "type": "count",
        "description": "Contracts where end_date IS NULL",
        "column": "id",
        "filter": {"end_date": None},
        "aggregations": ["count"],
        "format": "integer",
    },
    "dated_contract_count": {
        "type": "count",
        "description": "Contracts where end_date IS NOT NULL",
        "column": "id",
        "filter": {"end_date__not_null": True},
        "aggregations": ["count"],
        "format": "integer",
    },
    # ── Configuration features ────────────────────────────────────────────────
    "gst_contract_count": {
        "type": "count",
        "description": "Contracts with GST enabled (charge_gst = true)",
        "column": "id",
        "filter": {"charge_gst": True},
        "aggregations": ["count"],
        "format": "integer",
    },
    "no_gst_contract_count": {
        "type": "count",
        "description": "Contracts with GST disabled (charge_gst = false)",
        "column": "id",
        "filter": {"charge_gst": False},
        "aggregations": ["count"],
        "format": "integer",
    },
    "super_contract_count": {
        "type": "count",
        "description": "Contracts with superannuation configured (super_enabled = true)",
        "column": "id",
        "filter": {"super_enabled": True},
        "aggregations": ["count"],
        "format": "integer",
    },
    "holiday_rules_contract_count": {
        "type": "count",
        "description": "Contracts using holiday rules (holiday_rules_enabled = true)",
        "column": "id",
        "filter": {"holiday_rules_enabled": True},
        "aggregations": ["count"],
        "format": "integer",
    },
    "payment_calendar_contract_count": {
        "type": "count",
        "description": "Contracts tracking expected payments in a calendar",
        "column": "id",
        "filter": {"payment_calendar_enabled": True},
        "aggregations": ["count"],
        "format": "integer",
    },
    "has_rate_contract_count": {
        "type": "count",
        "description": "Contracts with at least one rate rule (min_hourly_rate IS NOT NULL)",
        "column": "id",
        "filter": {"min_hourly_rate__not_null": True},
        "aggregations": ["count"],
        "format": "integer",
    },
    "missing_customer_contract_count": {
        "type": "count",
        "description": "Contracts without a customer reference (customer_id IS NULL)",
        "column": "id",
        "filter": {"customer_id": None},
        "aggregations": ["count"],
        "format": "integer",
    },
    # ── Configuration health ──────────────────────────────────────────────────
    "warning_contract_count": {
        "type": "count",
        "description": "Contracts with configurationStatus = warning",
        "column": "id",
        "filter": {"configuration_status": "warning"},
        "aggregations": ["count"],
        "format": "integer",
    },
    "invalid_contract_count": {
        "type": "count",
        "description": "Contracts with configurationStatus = invalid",
        "column": "id",
        "filter": {"configuration_status": "invalid"},
        "aggregations": ["count"],
        "format": "integer",
    },
    "complete_contract_count": {
        "type": "count",
        "description": "Contracts with configurationStatus = complete",
        "column": "id",
        "filter": {"configuration_status": "complete"},
        "aggregations": ["count"],
        "format": "integer",
    },
    # ── Rate metrics ──────────────────────────────────────────────────────────
    "min_hourly_rate": {
        "type": "currency",
        "description": "Minimum hourly rate across contracts in scope",
        "column": "min_hourly_rate",
        "aggregations": ["min", "avg"],
        "format": "currency",
        "null_handling": "skip rows where min_hourly_rate IS NULL",
    },
    "max_hourly_rate": {
        "type": "currency",
        "description": "Maximum hourly rate across contracts in scope",
        "column": "max_hourly_rate",
        "aggregations": ["max", "avg"],
        "format": "currency",
        "null_handling": "skip rows where max_hourly_rate IS NULL",
    },
    "avg_payment_terms_days": {
        "type": "numeric",
        "description": "Average payment terms in days (excludes scheduled-payment contracts)",
        "column": "payment_terms_days",
        "aggregations": ["avg"],
        "format": "days",
        "null_handling": "skip NULL rows (scheduled payment contracts)",
    },
}
