services:

  orchestrator:
    build:
      context: ./orchestrator
      args:
        NODE_ENV: prod
    container_name: orchestrator
    env_file: ./orchestrator/.env.prod
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      args:
        NODE_ENV: prod
    container_name: backend
    env_file: ./backend/.env.prod
    restart: unless-stopped

#  communication:
#    build:
#      context: ./communication
#      args:
#        NODE_ENV: prod
#    container_name: communication
#    env_file: ./communication/.env.prod
#    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        NODE_ENV: prod
    container_name: frontend
    depends_on:
      - backend
      - orchestrator
#      - communication
    restart: unless-stopped

    networks:
      - default
      - grapifly_proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.jtrade-frontend.rule=Host(`jtrade.grapifly.com`)"
      - "traefik.http.routers.jtrade-frontend.entrypoints=websecure"
      - "traefik.http.routers.jtrade-frontend.tls=true"
      - "traefik.http.routers.jtrade-frontend.tls.certresolver=le"

      - "traefik.http.services.jtrade-frontend.loadbalancer.server.port=80"


networks:

  grapifly_proxy:
    external: true
