export interface UpdateOrganizationDto {
  name?: string;
  entityType?: 'company' | 'individual';
  status?: 'active' | 'suspended' | 'archived';
  legalName?: string;
  tagline?: string;
  timezone?: string;
  officialEmail?: string;
  supportEmail?: string;
  supportPhoneCountryCode?: string;
  supportPhoneNumber?: string;
  supportHours?: string;
  addressLine1?: string;
  addressLine2?: string;
  addressCity?: string;
  addressState?: string;
  addressPostalCode?: string;
  addressCountry?: string;
  websiteUrl?: string;
  apiBaseUrl?: string;
  helpCenterUrl?: string;
  privacyPolicyUrl?: string;
  termsUrl?: string;
  unsubscribeUrl?: string;
  facebook?: string;
  instagram?: string;
  linkedin?: string;
  x?: string;
  youtube?: string;
  tiktok?: string;
  whatsapp?: string;
  telegram?: string;
  copyrightText?: string;
  disclaimerShort?: string;
  disclaimerLong?: string;
  logoIconUrl?: string;
  logoFullUrl?: string;
}
